# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(270, 0, 501, 541))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.scapprofile = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.scapprofile.setContentsMargins(1, 1, 1, 1)
        self.scapprofile.setObjectName("scapprofile")
        self.lblscapprofile = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblscapprofile.setObjectName("lblscapprofile")
        self.scapprofile.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblscapprofile)
        self.txtProfileTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtProfileTitle.setObjectName("txtProfileTitle")
        self.scapprofile.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtProfileTitle)
        self.lblprofiledesc = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblprofiledesc.setObjectName("lblprofiledesc")
        self.scapprofile.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblprofiledesc)
        self.txtProfileDesc = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.txtProfileDesc.setObjectName("txtProfileDesc")
        self.scapprofile.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtProfileDesc)
        self.severityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.severityLabel.setObjectName("severityLabel")
        self.scapprofile.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.severityLabel)
        self.severityComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.severityComboBox.setObjectName("severityComboBox")
        self.scapprofile.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.severityComboBox)
        self.oCILClauseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.oCILClauseLabel.setObjectName("oCILClauseLabel")
        self.scapprofile.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.oCILClauseLabel)
        self.txtOCILclause = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtOCILclause.setObjectName("txtOCILclause")
        self.scapprofile.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtOCILclause)
        self.oCILLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.oCILLabel.setObjectName("oCILLabel")
        self.scapprofile.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.oCILLabel)
        self.txtOCIL = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.txtOCIL.setObjectName("txtOCIL")
        self.scapprofile.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtOCIL)
        self.oRationaleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.oRationaleLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.oRationaleLabel.setObjectName("oRationaleLabel")
        self.scapprofile.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.oRationaleLabel)
        self.txtRationale = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.txtRationale.setObjectName("txtRationale")
        self.scapprofile.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtRationale)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 256, 361))
        self.treeView.setSortingEnabled(False)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.treeView.header().setCascadingSectionResizes(True)
        self.treeView.header().setHighlightSections(True)
        self.treeView.header().setSortIndicatorShown(False)
        self.treeView.header().setStretchLastSection(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(600, 550, 164, 21))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setStatusTip("")
        font = QtGui.QFont()
        self.actionQuit.setFont(font)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenSCAP Writer"))
        self.lblscapprofile.setText(_translate("MainWindow", "Title"))
        self.lblprofiledesc.setText(_translate("MainWindow", "Profile Description"))
        self.severityLabel.setText(_translate("MainWindow", "Severity"))
        self.oCILClauseLabel.setText(_translate("MainWindow", "OCIL Clause"))
        self.oCILLabel.setText(_translate("MainWindow", "OCIL"))
        self.oRationaleLabel.setText(_translate("MainWindow", "Rationale"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))

