# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 281, 431))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.treeView = QtWidgets.QTreeView(self.groupBox)
        self.treeView.setGeometry(QtCore.QRect(10, 60, 261, 361))
        self.treeView.setTabKeyNavigation(False)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setSortingEnabled(False)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.treeView.header().setCascadingSectionResizes(True)
        self.treeView.header().setHighlightSections(True)
        self.treeView.header().setSortIndicatorShown(False)
        self.treeView.header().setStretchLastSection(True)
        self.filedirsearch = QtWidgets.QLineEdit(self.groupBox)
        self.filedirsearch.setGeometry(QtCore.QRect(52, 30, 221, 23))
        self.filedirsearch.setInputMethodHints(QtCore.Qt.ImhNone)
        self.filedirsearch.setObjectName("filedirsearch")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(280, 20, 531, 581))
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 541))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.scapprofile = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.scapprofile.setContentsMargins(1, 1, 1, 1)
        self.scapprofile.setObjectName("scapprofile")
        self.lblscapprofile = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblscapprofile.setObjectName("lblscapprofile")
        self.scapprofile.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblscapprofile)
        self.txtProfileTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtProfileTitle.setObjectName("txtProfileTitle")
        self.scapprofile.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtProfileTitle)
        self.lblprofiledesc = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblprofiledesc.setObjectName("lblprofiledesc")
        self.scapprofile.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblprofiledesc)
        self.txtProfileDesc = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.txtProfileDesc.setObjectName("txtProfileDesc")
        self.scapprofile.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtProfileDesc)
        self.severityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.severityLabel.setObjectName("severityLabel")
        self.scapprofile.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.severityLabel)
        self.severityComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.severityComboBox.setObjectName("severityComboBox")
        self.scapprofile.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.severityComboBox)
        self.oCILClauseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.oCILClauseLabel.setObjectName("oCILClauseLabel")
        self.scapprofile.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.oCILClauseLabel)
        self.txtOCILclause = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtOCILclause.setObjectName("txtOCILclause")
        self.scapprofile.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtOCILclause)
        self.oCILLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.oCILLabel.setObjectName("oCILLabel")
        self.scapprofile.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.oCILLabel)
        self.txtOCIL = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.txtOCIL.setObjectName("txtOCIL")
        self.scapprofile.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtOCIL)
        self.oRationaleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.oRationaleLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.oRationaleLabel.setObjectName("oRationaleLabel")
        self.scapprofile.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.oRationaleLabel)
        self.txtRationale = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.txtRationale.setObjectName("txtRationale")
        self.scapprofile.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtRationale)
        #self.tabWidget.addTab(self.tab, "")
        #self.tab_2 = QtWidgets.QWidget()
        #self.tab_2.setObjectName("tab_2")
        #self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setStatusTip("")
        font = QtGui.QFont()
        self.actionQuit.setFont(font)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCAP Writer"))
        self.label.setText(_translate("MainWindow", "Search"))
        self.lblscapprofile.setText(_translate("MainWindow", "Title"))
        self.lblprofiledesc.setText(_translate("MainWindow", "Profile Description"))
        self.severityLabel.setText(_translate("MainWindow", "Severity"))
        self.oCILClauseLabel.setText(_translate("MainWindow", "OCIL Clause"))
        self.oCILLabel.setText(_translate("MainWindow", "OCIL"))
        self.oRationaleLabel.setText(_translate("MainWindow", "Rationale"))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))

